root: public/
vnu:
  - --also-check-css
ignore_re:
  - 'Element "style" not allowed as child of element "main"'
  - '"font-weight": .* is not a "font-weight" value'
  - 'Property "border-block"'
  - 'Property "color-scheme"'
  - 'Property "aspect-ratio"'
  - 'Property "margin-inline"'
  - 'Property "padding-inline"'
  - '"mask": Too many values'
  - 'pseudo-element or pseudo-class ":has"'
  - 'pseudo-element or pseudo-class ":is"'
  - 'CSS: Parse Error'
  - 'error: CSS: .* "revert" is not a .* value.'
  - 'Property "paint-order"'
  - 'Property "size-adjust"'
  - 'Property "ascent-override"'
  - 'Property "descent-override"'
  - 'Property "line-gap-override"'
  - 'Bad value "auto" for attribute "sizes"'
  - 'Attribute "fetchpriority" not allowed on element "img"'
