baseURL = 'https://david.alvarezrosa.com/'
title = 'David Álvarez Rosa | Personal Site'
disableHugoGeneratorInject = true
enableRobotsTXT = false
disableKinds = ['taxonomy', 'term']

[params]
  description = 'Personal site of David Álvarez Rosa'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 30

  [[menus.main]]
    name = 'RSS'
    url = '/index.xml'
    weight = 40

[imaging]
  quality = 50

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.highlight]
    noClasses = false
    style = "modus-operandi"
    lineNumbers = true

[module]
  [[module.mounts]]
    source = 'static'
    target = 'static'
  [[module.mounts]]
    source = 'COPYING'
    target = 'static/COPYING'
  [[module.mounts]]
    source = 'LICENSE'
    target = 'static/LICENSE'
