#+startup: logdone
#+macro: marginnote @@hugo:{{< marginnote >}}$1{{< /marginnote >}}@@
#+macro: sidenote @@hugo:{{< sidenote >}}$1{{< /sidenote >}}@@
#+macro: marginfig @@hugo:{{< figure src="/ox-hugo/$1" width="margin" caption="$2" >}}@@

* DONE Welcome!                                             :tag1:@category1:
CLOSED: [2025-11-25 Tue 09:31]
:PROPERTIES:
:EXPORT_FILE_NAME: my-first-post
:END:
Welcome to this website!

* DONE David Álvarez Rosa
:PROPERTIES:
:EXPORT_FILE_NAME: about
:EXPORT_HUGO_LAYOUT: about
:END:
:LOGBOOK:
- State "DONE"       from "TODO"       [2025-11-25 Tue 09:27]
- State "TODO"       from              [2025-11-25 Tue 09:27]
:END:

{{{marginfig(portrait.png, **That's me!** March 2022.)}}}
Software engineer with experience in low-latency systems, electronic
trading, and HFT infrastructure. Currently at Susquehanna.  Strong
advocate of free (as in /freedom/) software and devoted Emacs user.

Previously designed and implemented embedded systems at Amazon impacting
10M+ monthly active customers, developed semantic caching for LLMs at
Sopra Steria, and conducted quantitative analysis of cybersecurity risks
at Deloitte.

Holds a BSc in Mathematics, a BEng in Industrial Engineering, and a MSc
in Artificial Intelligence.

** Experience
*Software Engineer* --- Susquehanna
{{{marginnote(Jul 2024--Present<br/>Dublin\, Ireland)}}}\\
High-frequency options trading.  Low-latency market data and
trading signals.  Mentor and interviewer.

*Software Engineer II* --- Amazon
{{{marginnote(Mar 2022--Aug 2024<br/>Madrid\, Spain)}}}\\
Won org hackathon. Contributed to 100+ internal repos.  Designed systems
for 10M+ monthly active customers.  Promoted in 18 months (top 5%).
Mentored 3.  On-call.  Interviewer.

*Machine Learning Engineer* --- Sopra Steria
{{{marginnote(Apr 2024--Jul 2024<br/>Remote)}}}\\
Researched, designed, and built a semantic cache for LLMs.

*Risk Analyst* --- Deloitte
{{{marginnote(Sep 2021--Mar 2022<br/>Madrid\, Spain)}}}\\
Quantitative analysis of technological and cybersecurity risks for
top-tier banking companies.

*Visiting Researcher* --- Vector Institute
{{{marginnote(Sep 2020--Jun 2021<br/>Toronto\, Canada)}}}\\
Research thesis on multimodal learning (recomprehension.com).

*Machine Learning Engineer* --- BCN eMotorsport
{{{marginnote(Sep 2019--Feb 2020<br/>Barcelona\, Spain)}}}\\
Perception at Driverless UPC.  I served as LiDAR lead and collaborated
on computer vision for a fully autonomous car.

** Education
*MSc in Artificial Intelligence* --- UNIR
{{{marginnote(GPA 9.00/10)}}}\\
Official study program focused on AI research and enabling PhD.

*MSc in Mathematics* --- UNED\\
Math-lover part-time student. Dropout (joined Amazon).

*Research Thesis* --- UofT
{{{marginnote(GPA 10/10 (A+))}}}\\
Research thesis on multimodal learning (recomprehension.com).

*BSc in Mathematics* --- UPC
{{{marginnote(GPA 8.12/10 (top 10%)<br/>Honors in 9 subjects)}}}\\
Rigorous and proof-oriented degree with a robust mathematical base.

*BEng in Industrial Engineering* --- UPC
{{{marginnote(GPA 8.03/10 (top 2%)<br/>Honors in 14 subjects)}}}\\
Multidisciplinary and integrative vision of industrial engineering.

** Licenses & certifications
*Certificate in Advanced English (C1)* --- Cambridge University\\
*Machine Learning* --- Stanford University\\
*Deep Learning* --- deeplearning.ai\\
*Blockchain & Financial Technology* --- Hong Kong University\\
*Nova Talent Member* --- Nova

** Volunteering
*Mathematics Tutor*\\
Academic training for the Mathematical Olympiads.

*Volunteer* --- Banco de Alimentos\\
Food collection for people in need.

** Honors & awards
*General Scholarship* --- Government of Spain\\
Full university tuition plus an annual stipend (€11k).

*Mobility Scholarship* --- Cellex (CFIS)
{{{marginnote(Canceled due to Covid-19)}}}\\
Scholarship to carry out my research thesis at Toronto (€6k).

*Spanish Mathematical Olympiad*\\
Silver in local (Pamplona), honors in national (Barcelona).

*Spanish Physics Olympiad*\\
Gold in local (Pamplona), silver in national (Seville).

*Tuition and Housing Scholarship*  --- Cellex (CFIS)\\
University tuition and housing (€19k).

** Languages
*English* --- Proficient\\
*Spanish* --- Native\\
*Catalan* --- Intermediate
